services:
  - type: web
    name: musicbot
    runtime: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING_1
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_URI
        value: sqlite:///./data/bot.db
      - key: SQLITE_CACHE_PATH
        value: ./data/cache.db
      - key: MAX_QUEUE_SIZE
        value: 50
      - key: COMMAND_COOLDOWN
        value: 3
